export * from 'src/modules/informational-pages/common/dto/create-contact-method.dto';
export * from 'src/modules/informational-pages/common/dto/update-contact-method.dto';
export * from 'src/modules/informational-pages/common/dto/create-faq-category.dto';
export * from 'src/modules/informational-pages/common/dto/update-faq-category.dto';
export * from 'src/modules/informational-pages/common/dto/create-faq-item.dto';
export * from 'src/modules/informational-pages/common/dto/update-faq-item.dto';
export * from 'src/modules/informational-pages/common/dto/static-page-param.dto';
export * from 'src/modules/informational-pages/common/dto/create-static-page.dto';
export * from 'src/modules/informational-pages/common/dto/update-static-page.dto';
